# Generated by Django 4.1.5 on 2023-04-26 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Footer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Address', models.CharField(max_length=600)),
                ('telephone', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='shop_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.ImageField(upload_to='static/shop')),
                ('name', models.CharField(max_length=50)),
                ('Description', models.CharField(max_length=1000)),
                ('price', models.CharField(max_length=10)),
                ('mrp', models.CharField(max_length=10)),
                ('category_one', models.CharField(max_length=100)),
                ('category_two', models.CharField(max_length=100)),
                ('category_three', models.CharField(max_length=100)),
                ('special', models.CharField(max_length=20)),
            ],
        ),
    ]
