# Generated by Django 4.1.5 on 2023-04-26 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Username', models.CharField(max_length=100, verbose_name='Username')),
                ('Password', models.CharField(max_length=100, verbose_name='Password')),
            ],
        ),
        migrations.CreateModel(
            name='signup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Username', models.CharField(max_length=100, verbose_name='Username')),
                ('Email', models.CharField(max_length=100, verbose_name='Email')),
                ('Password', models.CharField(max_length=100, verbose_name='Password')),
            ],
        ),
    ]
