# Generated by Django 4.1.5 on 2023-04-26 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50, verbose_name='name')),
                ('Email', models.CharField(max_length=100, verbose_name='email')),
                ('Subject', models.CharField(max_length=100, verbose_name='subject')),
                ('Message', models.CharField(max_length=500, verbose_name='message')),
            ],
        ),
        migrations.CreateModel(
            name='contact_about',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Information', models.CharField(max_length=400)),
                ('Location', models.CharField(max_length=500)),
                ('Email', models.CharField(max_length=500)),
                ('Telephone', models.CharField(max_length=100)),
            ],
        ),
    ]
