# Generated by Django 4.1.5 on 2023-04-26 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banner_img', models.ImageField(upload_to='static/index/banner_img')),
            ],
        ),
        migrations.CreateModel(
            name='books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.ImageField(upload_to='static/books')),
                ('name', models.CharField(max_length=50)),
                ('price', models.CharField(max_length=10)),
                ('mrp', models.CharField(max_length=10)),
                ('category_one', models.CharField(max_length=100)),
                ('category_two', models.CharField(max_length=100)),
                ('special', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='carousel_1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carousel_img', models.ImageField(upload_to='static/index/carousel_image1')),
                ('title', models.CharField(max_length=250)),
                ('sub_title', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='carousel_2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carousel_img', models.ImageField(upload_to='static/index/carousel_image2')),
                ('title', models.CharField(max_length=250)),
                ('sub_title', models.CharField(max_length=250)),
                ('sub_sub_title', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='carousel_3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carousel_img', models.ImageField(upload_to='static/index/carousel_image3')),
                ('title', models.CharField(max_length=250)),
                ('sub_title', models.CharField(max_length=250)),
                ('sub_sub_title', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='consumer_electronics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.ImageField(upload_to='static/consumer_electronics')),
                ('name', models.CharField(max_length=50)),
                ('price', models.CharField(max_length=10)),
                ('mrp', models.CharField(max_length=10)),
                ('category_one', models.CharField(max_length=100)),
                ('category_two', models.CharField(max_length=100)),
                ('special', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='men_banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banner', models.ImageField(upload_to='static/index/men_banner')),
            ],
        ),
        migrations.CreateModel(
            name='men_hot_deals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.ImageField(upload_to='static/index/men_hot_deals')),
                ('name', models.CharField(max_length=50)),
                ('price', models.CharField(max_length=10)),
                ('mrp', models.CharField(max_length=10)),
                ('category_one', models.CharField(max_length=100)),
                ('category_two', models.CharField(max_length=100)),
                ('category_three', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='men_latest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.ImageField(upload_to='static/index/men_latest')),
                ('name', models.CharField(max_length=50)),
                ('price', models.CharField(max_length=10)),
                ('mrp', models.CharField(max_length=10)),
                ('category_one', models.CharField(max_length=100)),
                ('category_two', models.CharField(max_length=100)),
                ('special', models.CharField(max_length=20)),
                ('category_three', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='men_top_rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.ImageField(upload_to='static/index/men_top_rating')),
                ('name', models.CharField(max_length=50)),
                ('price', models.CharField(max_length=10)),
                ('mrp', models.CharField(max_length=10)),
                ('category_one', models.CharField(max_length=100)),
                ('category_two', models.CharField(max_length=100)),
                ('category_three', models.CharField(max_length=100)),
                ('special', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='mobiles_tablets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.ImageField(upload_to='static/mobiles_tablets')),
                ('name', models.CharField(max_length=50)),
                ('price', models.CharField(max_length=10)),
                ('mrp', models.CharField(max_length=10)),
                ('category_one', models.CharField(max_length=100)),
                ('category_two', models.CharField(max_length=100)),
                ('special', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='single',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.ImageField(upload_to='static/index/men_top_rating')),
                ('title', models.CharField(max_length=500)),
                ('category_one', models.CharField(max_length=100)),
                ('category_two', models.CharField(max_length=100)),
                ('category_three', models.CharField(max_length=100)),
                ('category_four', models.CharField(max_length=100)),
                ('Description', models.CharField(max_length=900)),
                ('price', models.CharField(max_length=100)),
                ('mrp', models.CharField(max_length=100)),
                ('Discount', models.CharField(max_length=100)),
                ('Save', models.CharField(max_length=100)),
                ('Only', models.CharField(max_length=100)),
                ('Available_Color', models.CharField(max_length=100)),
                ('Available_Size', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='single_product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.ImageField(upload_to='static/index/men_top_rating')),
            ],
        ),
        migrations.CreateModel(
            name='smartwatches',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.ImageField(upload_to='static/smartwatches')),
                ('name', models.CharField(max_length=50)),
                ('price', models.CharField(max_length=10)),
                ('mrp', models.CharField(max_length=10)),
                ('category_one', models.CharField(max_length=100)),
                ('category_two', models.CharField(max_length=100)),
                ('special', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='toys_latest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.ImageField(upload_to='static/toys_latest')),
                ('name', models.CharField(max_length=50)),
                ('price', models.CharField(max_length=10)),
                ('mrp', models.CharField(max_length=10)),
                ('category_one', models.CharField(max_length=100)),
                ('category_two', models.CharField(max_length=100)),
                ('category_three', models.CharField(max_length=100)),
                ('special', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='toys_top_rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.ImageField(upload_to='static/toys_top_rating')),
                ('name', models.CharField(max_length=50)),
                ('price', models.CharField(max_length=10)),
                ('mrp', models.CharField(max_length=10)),
                ('category_one', models.CharField(max_length=100)),
                ('category_two', models.CharField(max_length=100)),
                ('category_three', models.CharField(max_length=100)),
                ('special', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='tv',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.ImageField(upload_to='static/tv')),
                ('name', models.CharField(max_length=50)),
                ('price', models.CharField(max_length=10)),
                ('mrp', models.CharField(max_length=10)),
                ('category_one', models.CharField(max_length=100)),
                ('category_two', models.CharField(max_length=100)),
                ('special', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='women_latest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.ImageField(upload_to='static/index/women_latest')),
                ('name', models.CharField(max_length=50)),
                ('price', models.CharField(max_length=10)),
                ('mrp', models.CharField(max_length=10)),
                ('category_one', models.CharField(max_length=100)),
                ('category_two', models.CharField(max_length=100)),
                ('category_three', models.CharField(max_length=100)),
                ('special', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='women_top_rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.ImageField(upload_to='static/women_top_rating')),
                ('name', models.CharField(max_length=50)),
                ('price', models.CharField(max_length=10)),
                ('mrp', models.CharField(max_length=10)),
                ('category_one', models.CharField(max_length=100)),
                ('category_two', models.CharField(max_length=100)),
                ('category_three', models.CharField(max_length=100)),
                ('special', models.CharField(max_length=20)),
            ],
        ),
    ]
