# Generated by Django 4.1.5 on 2023-05-03 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='add_to_cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100, verbose_name='name')),
                ('product_price', models.CharField(max_length=100, verbose_name='price')),
                ('product_Quantity', models.CharField(max_length=100, verbose_name='Quantity')),
            ],
        ),
    ]
